ECHO --------------
ECHO VC2022 VERSION
ECHO --------------

set XHB_VC2022=\xharbour
SET _XB_Compiler=vc2022
SET _XB_NonDebug=-NoXbp
SET _XB_Debug=-NoXbp -Debug
SET _XB_Exe=%_XB_NonDebug%

SET _BUILD_MT=YES
SET _BUILD_DEBUG=NO

SET _BUILD_DEMO=NO
SET _BUILD_PERSONAL=NO
SET _BUILD_PROF=NO
SET _BUILD_XHB_EXE=YES
SET _BUILD_XHB_LIB=YES
SET _BUILD_XHB_DLL=YES
SET _BUILD_CORE=NO
SET _BUILD_XBUILD=YES
SET _BUILD_CONTRIB=NO
SET _BUILD_DMAIN_LIB=NO
SET _BUILD_VXHDLL=YES
SET _BUILD_HBZLIB=YES
SET _BUILD_XHBCOMM=YES
SET _BUILD_ADS=YES
SET _BUILD_BGD=YES
SET _BUILD_XDO_DLL=YES
SET _BUILD_IEGUI_LIB=NO
SET _BUILD_DBG_CLIENT=YES

SET _BUILD_TPROJECT_LIB=YES
SET _BUILD_XEDIT_LIB=YES

SET _BUILD_APOLLORDD=YES
SET _BUILD_WINAPI_LIB=YES
SET _BUILD_XBSCRIPT_LIB=YES
SET _BUILD_CT3COMM=YES
SET _BUILD_ACTIVEX=YES
SET _BUILD_RMDBFCDX=YES
SET _BUILD_WINCORE=YES
SET _BUILD_OLE=YES
SET _BUILD_SQLRDD=YES

SET _BUILD_XBUILDW_AS=EXE
SET _BUILD_VXH_AS=EXE
SET _BUILD_XEDITW_AS=DLL
SET _BUILD_XPROMPT_AS=DLL
SET _BUILD_XDEBUGW_AS=DLL


IF "%VC2022_MT%"=="YES"           SET _BUILD_MT=YES
IF "%VC2022_MT%"=="NO"            SET _BUILD_MT=NO

IF "%VC2022_DEMO%"=="YES"         SET _BUILD_DEMO=YES
IF "%VC2022_DEMO%"=="NO"          SET _BUILD_DEMO=NO

IF "%VC2022_PERSONAL%"=="YES"     SET _BUILD_PERSONAL=YES
IF "%VC2022_PERSONAL%"=="NO"      SET _BUILD_PERSONAL=NO

IF "%VC2022_PROF%"=="YES"         SET _BUILD_PROF=YES
IF "%VC2022_PROF%"=="NO"          SET _BUILD_PROF=NO

IF "%VC2022_XHB_EXE%"=="YES"      SET _BUILD_XHB_EXE=YES
IF "%VC2022_XHB_EXE%"=="NO"       SET _BUILD_XHB_EXE=NO

IF "%VC2022_XHB_LIB%"=="YES"      SET _BUILD_XHB_LIB=YES
IF "%VC2022_XHB_LIB%"=="NO"       SET _BUILD_XHB_LIB=NO

IF "%VC2022_XHB_DLL%"=="YES"      SET _BUILD_XHB_DLL=YES
IF "%VC2022_XHB_DLL%"=="NO"       SET _BUILD_XHB_DLL=NO

IF "%VC2022_CORELIBS%"=="YES"     SET _BUILD_CORE=YES
IF "%VC2022_CORELIBS%"=="NO"      SET _BUILD_CORE=NO

IF "%VC2022_XBUILD%"=="YES"       SET _BUILD_XBUILD=YES
IF "%VC2022_XBUILD%"=="NO"        SET _BUILD_XBUILD=NO

IF "%VC2022_CONTRIB%"=="YES"      SET _BUILD_CONTRIB=YES
IF "%VC2022_CONTRIB%"=="NO"       SET _BUILD_CONTRIB=NO

IF "%VC2022_DMAIN_LIB%"=="YES"    SET _BUILD_DMAIN_LIB=YES
IF "%VC2022_DMAIN_LIB%"=="NO"     SET _BUILD_DMAIN_LIB=NO

IF "%VC2022_VXHDLL%"=="YES"       SET _BUILD_VXHDLL=YES
IF "%VC2022_VXHDLL%"=="NO"        SET _BUILD_VXHDLL=NO

IF "%VC2022_SQLRDD%"=="YES"       SET _BUILD_SQLRDD=YES
IF "%VC2022_SQLRDD%"=="NO"        SET _BUILD_SQLRDD=NO

IF "%VC2022_HBZLIB%"=="YES"       SET _BUILD_HBZLIB=YES
IF "%VC2022_HBZLIB%"=="NO"        SET _BUILD_HBZLIB=NO

IF "%VC2022_CT3COMM%"=="YES"      SET _BUILD_CT3COMM=YES
IF "%VC2022_CT3COMM%"=="NO"       SET _BUILD_CT3COMM=NO

IF "%VC2022_XHBCOMM%"=="YES"      SET _BUILD_XHBCOMM=YES
IF "%VC2022_XHBCOMM%"=="NO"       SET _BUILD_XHBCOMM=NO

IF "%VC2022_APOLLORDD%"=="YES"    SET _BUILD_APOLLORDD=YES
IF "%VC2022_APOLLORDD%"=="NO"     SET _BUILD_APOLLORDD=NO

IF "%VC2022_WINAPI_LIB%"=="YES"   SET _BUILD_WINAPI_LIB=YES
IF "%VC2022_WINAPI_LIB%"=="NO"    SET _BUILD_WINAPI_LIB=NO

IF "%VC2022_TPROJECT_LIB%"=="YES" SET _BUILD_TPROJECT_LIB=YES
IF "%VC2022_TPROJECT_LIB%"=="NO"  SET _BUILD_TPROJECT_LIB=NO

IF "%VC2022_XEDIT_LIB%"=="YES"    SET _BUILD_XEDIT_LIB=YES
IF "%VC2022_XEDIT_LIB%"=="NO"     SET _BUILD_XEDIT_LIB=NO

IF "%VC2022_XDO_DLL%"=="YES"      SET _BUILD_XDO_DLL=YES
IF "%VC2022_XDO_DLL%"=="NO"       SET _BUILD_XDO_DLL=NO

IF "%VC2022_IEGUI_LIB%"=="YES"    SET _BUILD_IEGUI_LIB=YES
IF "%VC2022_IEGUI_LIB%"=="NO"     SET _BUILD_IEGUI_LIB=NO

IF "%VC2022_DBG_CLIENT%"=="YES"   SET _BUILD_DBG_CLIENT=YES
IF "%VC2022_DBG_CLIENT%"=="NO"    SET _BUILD_DBG_CLIENT=NO

IF "%VC2022_BGD%"=="YES"          SET _BUILD_BGD=YES
IF "%VC2022_BGD%"=="NO"           SET _BUILD_BGD=NO

IF "%VC2022_XBSCRIPT_LIB%"=="YES" SET _BUILD_XBSCRIPT_LIB=YES
IF "%VC2022_XBSCRIPT_LIB%"=="NO"  SET _BUILD_XBSCRIPT_LIB=NO

IF "%VC2022_WINCORE%"=="YES"      SET _BUILD_WINCORE=YES
IF "%VC2022_WINCORE%"=="NO"       SET _BUILD_WINCORE=NO

IF "%VC2022_DEBUG%"=="YES"        SET _XB_Exe=%_XB_Debug%
IF "%VC2022_DEBUG%"=="NO"         SET _XB_Exe=%_XB_NonDebug%
IF "%VC2022_DEBUG%"=="YES"        SET _BUILD_DEBUG=YES
IF "%VC2022_DEBUG%"=="NO"         SET _BUILD_DEBUG=NO
IF "%VC2022_DEBUG%"=="NO"         SET _XB_Debug=%_XB_NonDebug%

IF "%VC2022_XBUILDW_AS%"=="DLL"   SET _BUILD_XBUILDW_AS=DLL
IF "%VC2022_XBUILDW_AS%"=="EXE"   SET _BUILD_XBUILDW_AS=EXE
IF "%VC2022_XBUILDW_AS%"=="NONE"  SET _BUILD_XBUILDW_AS=NONE

IF "%VC2022_VXH_AS%"=="DLL"       SET _BUILD_VXH_AS=DLL
IF "%VC2022_VXH_AS%"=="EXE"       SET _BUILD_VXH_AS=EXE
IF "%VC2022_VXH_AS%"=="NONE"      SET _BUILD_VXH_AS=NONE

IF "%VC2022_XEDITW_AS%"=="DLL"    SET _BUILD_XEDITW_AS=DLL
IF "%VC2022_XEDITW_AS%"=="EXE"    SET _BUILD_XEDITW_AS=EXE
IF "%VC2022_XEDITW_AS%"=="NONE"   SET _BUILD_XEDITW_AS=NONE

IF "%VC2022_XDEBUGW_AS%"=="DLL"   SET _BUILD_XDEBUGW_AS=DLL
IF "%VC2022_XDEBUGW_AS%"=="EXE"   SET _BUILD_XDEBUGW_AS=EXE
IF "%VC2022_XDEBUGW_AS%"=="NONE"  SET _BUILD_XDEBUGW_AS=NONE

IF "%VC2022_XPROMPT_AS%"=="DLL"   SET _BUILD_XPROMPT_AS=DLL
IF "%VC2022_XPROMPT_AS%"=="EXE"   SET _BUILD_XPROMPT_AS=EXE
IF "%VC2022_XPROMPT_AS%"=="NONE"  SET _BUILD_XPROMPT_AS=NONE


SET _XHB_LIB=\xHB\lib\%_XB_Compiler%
SET _XHB_BIN=\xHB\bin\%_XB_Compiler%
SET _XHB_DLL=\xHB\dll\%_XB_Compiler%

ECHO ON
